### ISSUE TITLE
Bug: User can visit /register even after logged in

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#162]
**Describe the bug**
Although, we remove the Register button form the UI when a user is logged in, still a logged in user can go to /register route from the url bar. 

**To Reproduce**
1. Go to Home page and login/register.
2. Go to /register route from url bar

**Expected behavior**
Once a user is logged in, they should not be able to visit register page by any way. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54268438/105892783-54ad2300-6038-11eb-9c0c-fa791153734f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version :  88.0.4324.104

**Additional context**
Although, if we go to /login route it works as expected and redirects to home page. Register page should also work the same way. 

I would like to take up this issue.

**Comment by chinmaym07** [comment]
@Rahulm2310 I think this issue is solved by #157  please check this.

**Comment by Rahulm2310** [comment]
@chinmaym07 No, I replicated the changes from the PR locally and tried but it is not fixed. #157 only fixes the issue of not showing logout button. This issue still persists. You can try

**Comment by chinmaym07** [comment]
@Rahulm2310 please look at this 
https://github.com/anitab-org/bridge-in-tech-web/pull/157#pullrequestreview-578021021
I have added a gif for more info.

**Comment by Rahulm2310** [comment]
@chinmaym07 I totally get your point, but the issue I have mentioned is different. It is not about the logout button. 
User can go to /register route via URL bar and no redirect happens.

**Comment by chinmaym07** [comment]
> @chinmaym07 I totally get your point, but the issue I have mentioned is different. It is not about the logout button. 
> User can go to /register route via URL bar and no redirect happens. 

Yes that's correct.. ☺️👍🏻

**Comment by mtreacy002** [comment]
@Rahulm2310 . Spot on 👍👍. Will assign this to you 😉
